import styled from 'styled-components'
import LayoutClient from './LayoutClient'
import './globals.css'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import '@fortawesome/fontawesome-free/css/all.min.css'
import StyledComponentsRegistry from './lib/registry'
import { LinearProgress } from '@mui/material';
import { appState } from './redux/types';
import { useSelector } from 'react-redux';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LayoutClient>
        <body className={inter.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          </body>
      </LayoutClient>
    </html>
  )
}
